module.exports = {
  content: [
    "./index.html",
    "./src/*.vue",
    "./src/**/*.vue",
    "./src/**/**/*.vue",
    "./src/**/**/**/*.vue",
  ],
  theme: {
    fontFamily: {
      poppins: ["Poppins", "sans-serif"],
      "abril-fatface": ["Abril Fatface", "cursive"],
      anybody: ["Anybody", "cursive"],
      astloch: ["Astloch", "cursive"],
      aubrey: ["Aubrey", "cursive"],
      "bebas-neue": ["Bebas Neue", "cursive"],
      "big-shoulders-inline-text": ["Big Shoulders Inline Text", "cursive"],
      butcherman: ["Butcherman", "cursive"],
      comfortaa: ["Comfortaa", "cursive"],
      fasthand: ["Fasthand", "cursive"],
      federant: ["Federant", "cursive"],
      "fredoka-one": ["Fredoka One", "cursive"],
      fruktur: ["Fruktur", "cursive"],
      geostar: ["Geostar", "cursive"],
      "geostar-fill": ["Geostar Fill", "cursive"],
      hanalei: ["Hanalei", "cursive"],
      kenia: ["Kenia", "cursive"],
      langar: ["Langar", "cursive"],
      lobster: ["Lobster", "cursive"],
      miltonian: ["Miltonian", "cursive"],
      "miltonian-tattoo": ["Miltonian Tattoo", "cursive"],
      moulpali: ["Moulpali", "cursive"],
      "nova-cut": ["Nova Cut", "cursive"],
      "nova-oval": ["Nova Oval", "cursive"],
      "nova-script": ["Nova Script", "cursive"],
      oi: ["Oi", "cursive"],
      "passero-one": ["Passero One", "cursive"],
      "purple-purse": ["Purple Purse", "cursive"],
      "rubik-bubbles": ["Rubik Bubbles", "cursive"],
      "rubik-glitch": ["Rubik Glitch", "cursive"],
      "rubik-microbe": ["Rubik Microbe", "cursive"],
      "rubik-moonrocks": ["Rubik Moonrocks", "cursive"],
      "rubik-puddles": ["Rubik Puddles", "cursive"],
      "rubik-wet-paint": ["Rubik Wet Paint", "cursive"],
      sevillana: ["Sevillana", "cursive"],
      "single-day": ["Single Day", "cursive"],
      "snowburst-one": ["Snowburst One", "cursive"],
      "sofadi-one": ["Sofadi One", "cursive"],
      "stalinist-one": ["Stalinist One", "cursive"],
      taprom: ["Taprom", "cursive"],
      warnes: ["Warnes", "cursive"],
      "zen-tokyo-zoo": ["Zen Tokyo Zoo", "cursive"],
    },
    extend: {},
  },
  plugins: [],
};
